### ISSUE TITLE
如何由这些markdown文件生成html

### ISSUE THREAD

**Issue by clearw5** [nodejscn/node-api-cn#301]
我在做一个以JavaScript为语言的编程软件的文档，想直接使用Node.js文档的样式。
在node的github上找到一个[doc-tool](https://github.com/nodejs/doc-tool)但没有成功使用。
我猜这个项目应该有相应的工具和模板来生成网页。请问这些开源或者提供吗？
谢谢~

**Comment by h7lin** [comment]
markdown 文件使用 [marked](https://www.npmjs.com/package/marked) 生成的，模版跟样式文件在 https://github.com/nodejs/node/tree/master/doc
