### ISSUE TITLE
单词(module.expors)拼写错误

### ISSUE THREAD

**Issue by zm-john** [nodejscn/node-api-cn#48]
![image](https://cloud.githubusercontent.com/assets/16522311/25325490/52a6d512-28fe-11e7-997c-66da37082ab2.png)

[链接地址http://nodejs.cn/api/modules.html#modules_module_exports](http://nodejs.cn/api/modules.html#modules_module_exports)

**Comment by h7lin** [comment]
已修复。多谢支持。
