### ISSUE TITLE
排版错误

### ISSUE THREAD

**Issue by HuMoran** [nodejscn/node-api-cn#598]
环境：Ubuntu 18.04 chrome
发现很多地方应该是md的格式有问题，不能正常显示，如图
![image](https://user-images.githubusercontent.com/25628402/40155356-db6d9f36-59c5-11e8-81aa-4ffc8043da0e.png)
当鼠标放上后：
![image](https://user-images.githubusercontent.com/25628402/40155408-2a405770-59c6-11e8-8b45-d7b13a26dd6c.png)

**Comment by h7lin** [comment]
多谢指出，已经修复。
