### ISSUE TITLE
文档生成

### ISSUE THREAD

**Issue by nico1988** [nodejscn/node-api-cn#599]
比较奇怪很多开源框架的文档都是md，这里边是怎么做的转化，从md-html

**Comment by h7lin** [comment]
使用 [marked](https://www.npmjs.com/package/marked)。

**Comment by nico1988** [comment]
这个mared怎么结合github实现持续集成啊，比如我编辑github的md，应该有个后台勾子自动实现编译发布是么？

**Comment by h7lin** [comment]
在Settings里面设置Webhooks。
