### ISSUE TITLE
断言部分文档示例代码报错

### ISSUE THREAD

**Issue by Avenmemety** [nodejscn/node-api-cn#606]
const assert = require('assert');

// 生成一个 AssertionError，用于比较错误信息：
const { message } = new assert.AssertionError({
  actual: 1,
  expected: 2,
  operator: 'strictEqual'
});

// 验证输出的错误：
try {
  assert.strictEqual(1, 2);
} catch (err) {
  assert(err instanceof assert.AssertionError);
  assert.strictEqual(err.message, message);
  assert.strictEqual(err.name, 'AssertionError [ERR_ASSERTION]');
  assert.strictEqual(err.actual, 1);
  assert.strictEqual(err.expected, 2);
  assert.strictEqual(err.code, 'ERR_ASSERTION');
  assert.strictEqual(err.operator, 'strictEqual');
  assert.strictEqual(err.generatedMessage, true);
}

这里
![image](https://user-images.githubusercontent.com/22796600/40409922-ed1eaae4-5e9e-11e8-8c8f-feb8e9aa9472.png)

// 生成一个 AssertionError，用于比较错误信息：
const { message } = new assert.AssertionError({
  actual: 1,
  expected: 2,
  operator: '==='
});

// 验证输出的错误：
try {
  assert.strictEqual(1, 2);
} catch (err) {
  assert(err instanceof assert.AssertionError);
  assert.strictEqual(err.message, message);
  assert.strictEqual(err.name, 'AssertionError [ERR_ASSERTION]');
  assert.strictEqual(err.actual, 1);
  assert.strictEqual(err.expected, 2);
  assert.strictEqual(err.code, 'ERR_ASSERTION');
  assert.strictEqual(err.operator, '===');
  assert.strictEqual(err.generatedMessage, true);
}
这样子就没事了

**Comment by h7lin** [comment]
你的 node 版本应该是 v10.0 以下，这个示例在 v8.0 跟 v10.0 会有不同的结果。
