### ISSUE TITLE
如何修改无英文对照的文档

### ISSUE THREAD

**Issue by nodejh** [nodejscn/node-api-cn#655]
如图中的 JSON 输出

![image](https://user-images.githubusercontent.com/10287125/54740107-55333200-4bf5-11e9-9026-c4b497c4a8e0.png)

**Comment by h7lin** [comment]
这里最近正在改造，暂时关闭部分无中英对照的文档的翻译入口，很快就会重新放开。但处于试验阶段或废弃阶段的文档仍然不会开放入口，因为试验阶段的文档还不稳定未来可能会有较大变动。
