### ISSUE TITLE
Global Objects 错误翻译为 global

### ISSUE THREAD

**Issue by oceans-pro** [nodejscn/node-api-cn#675]
10.x的文档中，原翻译错误地将 Gloabl Object 与 global 混淆。这会给初学者带来很大的困扰。
![Global](https://user-images.githubusercontent.com/43755773/63178804-5d48ae00-c07d-11e9-8cec-c2b0202bcdd2.png)
![global 1](https://user-images.githubusercontent.com/43755773/63178541-d562a400-c07c-11e9-85ae-4daccb3293a4.png)

**Comment by h7lin** [comment]
多谢建议，因为这章大部分 API 都可通过 global 对象的属性访问，所以为了统一导航名称故意为之，我再好好想想有没有其他选择。
